### PR TITLE
Develop j

### PR DESCRIPTION
**Pull request by jguterl**
Tested for UEDGE on local linux machine and on NERSC cori cluster.

### CODE REVIEW

**Comment by dpgrote** [comment]
Hi @jguterl - Let me know when this is ready to be merged.

**Comment by jguterl** [comment]
This is ready for merging but I had some issues with autopep so there
could be one or two lines not properly formatted. Openmp flags must be
verified for the various compilers different from gfortran and ifort.

**Comment by dpgrote** [comment]
Hi @jguterl - This all looks ok and I'll merge it in. Thanks for doing the clean up and reorganizing. This looks like a nice addition to Forthon. For future reference though, in any new pull requests I would prefer that you not modify code that is not directly related to the new changes. Those extra changes make more work for me since there are more changes that I need to examine, and has the risk of introducing bugs.

**Comment by dpgrote** [comment]
Hi @jguterl - Note that I've made a number of small fixes in the master branch. Make sure that you merge these changes into your fork.

**Pull request merged**
